language: python

python:
    - "2.7"
    - "3.5"

env:
  - TOX_ENV=django18
  - TOX_ENV=django19
  - TOX_ENV=django110
  - TOX_ENV=coverage

install:
  - pip install tox 

script:
  - tox -e $TOX_ENV

matrix:
  exclude:
   - python: "3.5"
     env: TOX_ENV=django18
   - python: "3.5"
     env: TOX_ENV=django19
   - python: "3.5"
     env: TOX_ENV=coverage
   - python: "2.7"
     env: TOX_ENV=coverage
